Repository CA-G12/Share-Us, pull requests merged in 2022-11, with the labels that each got.

#77 Try formik on add event form
  client/package-lock.json
  client/src/components/AddEvent/index.tsx
  client/src/components/AddEventMap/mapContainer.tsx
  client/src/components/SearchResult/index.tsx
  client/src/components/UserProfile/index.tsx
  client/src/interfaces/IAddEventInitialValues.tsx
  src/validation/addEventValidate.ts
Labels: awaiting-review

#87 adding upload image and change place name input to handle data
  client/src/components/AddEvent/index.tsx
  client/src/components/AddEventMap/mapContainer.tsx
  client/src/components/Uploader/index.tsx
  client/src/interfaces/IAddEventInitialValues.tsx
  client/src/pages/Home/index.tsx
  client/src/validation/addEventValidate.ts
  src/controllers/EventsController.ts
  src/validation/addEventValidate.ts
  test/addEvent.test.ts
  test/filterEvents.test.ts
Labels: awaiting-review

#86 make chat page style
  client/src/components/ChatBox/Friends.tsx
  client/src/components/ChatBox/Messages.tsx
  client/src/components/ChatBox/SingleFriend.tsx
  client/src/components/ChatBox/StyledBadge.tsx
  client/src/components/ChatBox/index.tsx
  client/src/components/ChatBox/style.tsx
  client/src/components/UserAudience/index.tsx
  client/src/interfaces/index.tsx
  client/src/interfaces/props/IFriendChat.tsx
  client/src/interfaces/props/IMessagesProps.tsx
  client/src/pages/Chat/index.tsx
Labels: awaiting-review

#82 create notifications system by websocket.io
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/AddCommentsModal/index.tsx
  client/src/components/AddEvent/index.tsx
  client/src/components/ChatBox/index.tsx
  client/src/components/CommentsContainer/index.tsx
  client/src/components/EventCalendar/index.tsx
  client/src/components/EventDetailsHeader/index.tsx
  client/src/components/Navbar/index.tsx
  client/src/components/NotificationsList/Notifications.tsx
  client/src/components/NotificationsList/style.css
  client/src/components/SearchResult/index.tsx
  client/src/components/UserAudience/index.tsx
  client/src/components/UserProfile/index.tsx
  client/src/hooks/useAuth.tsx
  client/src/hooks/useFollowing.tsx
  client/src/index.tsx
  client/src/interfaces/props/INotificationsList.tsx
  client/src/pages/Home/index.tsx
  client/src/pages/Profile/index.tsx
  package-lock.json
  package.json
  src/app.ts
  src/controllers/UserProfileController.ts
  src/models/User.ts
  src/notificationSystem/mySocketInterface.ts
  src/notificationSystem/notification.socket.ts
  src/notificationSystem/serverSocket.ts
  src/routes/users/index.ts
  tsconfig.json
Labels: awaiting-review

#93 handle routes delete: /events/1/comments/1 in back and front and make tests
  client/src/components/Comment/index.tsx
  client/src/components/Comment/style.css
  client/src/components/CommentsContainer/index.tsx
  client/src/interfaces/props/CommentsProps.tsx
  src/config/messages.ts
  src/controllers/CommentsController.ts
  test/deleteComments.test.ts
Labels: awaiting-review

#94 preparing for deploying
  client/src/components/AddEventMap/mapContainer.tsx
  client/src/components/CommentsContainer/index.tsx
  client/src/components/Map/index.tsx
  client/src/components/Navbar/index.tsx
  client/src/interfaces/props/INotificationsList.tsx
  package-lock.json
  package.json
  src/app.ts
  src/config/environment.ts
  tsconfig.json
Labels: awaiting-review

#98 handle routes delete: /event/id in back and front and make tests
  client/src/components/EventCard/EventCard.tsx
  client/src/components/EventCard/index.tsx
  client/src/components/EventCard/style.css
  client/src/interfaces/props/EventCardProps.tsx
  src/config/messages.ts
  src/controllers/EventsController.ts
  src/routes/events/index.ts
  test/deleteEvents.test.ts
Labels: approved

#96 cerate chat system
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/AddEvent/index.tsx
  client/src/components/AddEvent/style.css
  client/src/components/ChatBox/Friends.tsx
  client/src/components/ChatBox/Messages.tsx
  client/src/components/ChatBox/SingleFriend.tsx
  client/src/components/ChatBox/index.tsx
  client/src/components/ChatBox/style.css
  client/src/components/ChatBox/style.tsx
  client/src/components/EventCard/EventCard.tsx
  client/src/components/EventCard/index.tsx
  client/src/components/JoinedInterestedPeopleModel.tsx/style.css
  client/src/components/Navbar/index.tsx
  client/src/components/NotificationsList/Notifications.tsx
  client/src/components/UserProfile/ProfileActions.tsx
  client/src/components/UserProfile/style.tsx
  client/src/context/startChat.tsx
  client/src/index.tsx
  client/src/interfaces/ICurrentUser.tsx
  client/src/interfaces/IMyMessages.tsx
  client/src/interfaces/IRealTimeMessages.tsx
  client/src/interfaces/IUser.tsx
  client/src/interfaces/index.tsx
  client/src/interfaces/props/IAddedEvent.tsx
  client/src/interfaces/props/IFriendChat.tsx
  client/src/interfaces/props/IMessagesProps.tsx
  client/src/pages/Home/index.tsx
  client/src/pages/Profile/index.tsx
  client/src/react-app-env.d.ts
  package-lock.json
  package.json
  src/app.ts
  src/controllers/Chat.ts
  src/controllers/FollowingSystem.ts
  src/controllers/UserProfileController.ts
  src/db/index.ts
  src/models/Chat.ts
  src/routes/FollowingSystem/index.ts
  src/routes/chat/index.ts
  src/routes/index.ts
  src/routes/users/index.ts
  src/webSocket/chat.socket.ts
  src/webSocket/mySocketInterface.ts
  src/webSocket/notification.socket.ts
  src/webSocket/serverSocket.ts
Labels: awaiting-review

#99 Log in and Sign up using google auth
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/UserProfile/index.tsx
  client/src/hooks/useAuth.tsx
  client/src/interfaces/IAuthContext.tsx
  client/src/interfaces/IUser.tsx
  client/src/pages/auth/GoogleAuth.tsx
  client/src/pages/auth/Login.tsx
  client/src/pages/auth/SignUp.tsx
  package-lock.json
  src/controllers/Auth.ts
  src/interfaces/payload.ts
  src/models/User.ts
  src/routes/auth/index.ts
Labels: awaiting-review

#102 start fixing bugs
  client/src/App.tsx
  client/src/components/AboutEvent/style.css
  client/src/components/AddCommentsModal/index.tsx
  client/src/components/ChatBox/Friends.tsx
  client/src/components/CommentsContainer/index.tsx
  client/src/components/EditProfile/index.tsx
  client/src/components/EventCard/index.tsx
  client/src/components/NotificationsList/Notifications.tsx
  client/src/components/Uploader/index.tsx
  client/src/hooks/useFollowing.tsx
  client/src/services/ApiService.ts
  src/controllers/EventsController.ts
  src/db/index.ts
Labels: in progress

#106 Fix homepage and navbar styling
  client/src/components/CapturePage/index.tsx
  client/src/components/CapturePage/style.css
  client/src/components/ChatBox/style.css
  client/src/components/EventCard/EventCard.tsx
  client/src/index.css
Labels: in progress

#110 make responsive chat
  client/package-lock.json
  client/src/components/ChatBox/Friends.tsx
  client/src/components/ChatBox/Messages.tsx
  client/src/components/ChatBox/SingleFriend.tsx
  client/src/components/ChatBox/index.tsx
  client/src/components/ChatBox/style.css
  client/src/components/ChatBox/style.tsx
Labels: awaiting-review

#112 Make responsive profile page
  client/src/components/UserProfile/ProfileActions.tsx
  client/src/components/UserProfile/index.tsx
  client/src/components/UserProfile/style.css
Labels: awaiting-review

#114 event details responsive
  client/src/components/AboutEvent/index.tsx
  client/src/components/AboutEvent/style.css
  client/src/components/Comment/style.css
  client/src/components/CommentsContainer/style.css
  client/src/components/EventCard/EventCard.tsx
  client/src/components/EventCard/style.css
  client/src/components/EventDetailsHeader/index.tsx
  client/src/components/EventDetailsHeader/style.css
  client/src/components/Map/style.css
  client/src/components/Timer/style.css
  client/src/index.css
  client/src/pages/EventDetails/style.css
  client/src/pages/auth/Login.tsx
  client/src/pages/auth/SignUp.tsx
  client/src/pages/auth/auth.css
Labels: awaiting-review

#116 Fix bugs
  client/src/App.tsx
  client/src/components/AddCommentsModal/index.tsx
  client/src/components/AddEvent/index.tsx
  client/src/components/AddEventMap/index.tsx
  client/src/components/AddEventMap/style.css
  client/src/components/CapturePage/style.css
  client/src/components/EditProfile/index.tsx
  client/src/components/JoinedInterestedPeopleModel.tsx/index.tsx
  client/src/components/Navbar/index.tsx
  client/src/components/UserAudience/index.tsx
  client/src/components/UserProfile/index.tsx
  client/src/index.css
Labels: awaiting-review

#117 Readme file for our project
  README.md
Labels: approved

#121 Edit production synchronization & add suggested events in the home page
  client/src/components/EventCard/index.tsx
  src/db/build.ts
Labels: approved

#104 craete the backend for google calendar
  client/.eslintrc.json
  client/src/components/AddCommentsModal/index.tsx
  client/src/components/CommentsContainer/index.tsx
  client/src/components/EventCard/index.tsx
  client/src/components/EventDetailsHeader/index.tsx
  client/src/components/EventDetailsHeader/style.css
  client/src/components/GoogleCalendar/index.tsx
  client/src/components/GoogleCalendar/style.css
  client/src/index.tsx
  client/src/pages/auth/GoogleAuth.tsx
  package-lock.json
  package.json
  src/config/environment.ts
  src/controllers/Auth.ts
  src/controllers/GoogleCalendar.ts
  src/db/FakeData/fakeData.json
  src/models/Event.ts
  src/models/JoinedPeople.ts
  src/models/User.ts
  src/routes/events/index.ts
  src/validation/googleCalendarValidate.ts
  test/filterEvents.test.ts
Labels: in progress

#123 Edit the googleRegister query to update over the tokens
  client/src/pages/auth/GoogleAuth.tsx
  src/controllers/Auth.ts
  src/controllers/UserProfileController.ts
  src/models/User.ts
Labels: awaiting-review

#125 Make changes on the id in verify me function
  src/controllers/Auth.ts
  src/interfaces/IUserRequest.ts
Labels: approved

#122 edit some styles and View the number of unread messages from each friend separately
  client/public/index.html
  client/src/components/AboutEvent/style.css
  client/src/components/AddCommentsModal/index.tsx
  client/src/components/AddEvent/index.tsx
  client/src/components/AddEvent/style.css
  client/src/components/ChatBox/Friends.tsx
  client/src/components/ChatBox/Messages.tsx
  client/src/components/ChatBox/SingleFriend.tsx
  client/src/components/ChatBox/index.tsx
  client/src/components/ChatBox/style.css
  client/src/components/ChatBox/style.tsx
  client/src/components/CommentsContainer/index.tsx
  client/src/components/CommentsContainer/style.css
  client/src/components/EventDetailsHeader/index.tsx
  client/src/components/EventDetailsHeader/style.css
  client/src/components/NotificationsList/Notifications.tsx
  client/src/components/UserProfile/style.css
  client/src/interfaces/IEventOwner.tsx
  client/src/interfaces/IUser.tsx
  client/src/interfaces/index.tsx
  client/src/validation/addEventValidate.ts
  package-lock.json
  package.json
  src/controllers/UserProfileController.ts
  src/models/User.ts
  src/validation/addEventValidate.ts
  src/webSocket/notification.socket.ts
Labels: awaiting-review
