Repository CA-G12/Share-Us, pull requests merged in 2022-10, with the labels that each got.

#2 Create file structure for the backend and frontend
  .env.example
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  client/.eslintrc.json
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/assets/.gitkeep
  client/src/components/.gitkeep
  client/src/helpers/.gitkeep
  client/src/index.tsx
  client/src/layouts/.gitkeep
  client/src/pages/.gitkeep
  client/src/routes/.gitkeep
  client/src/services/.gitkeep
  client/tsconfig.json
  package-lock.json
  package.json
  src/app.ts
  src/config/.gitkeep
  src/config/environment.ts
  src/controllers/.gitkeep
  src/db/.gitkeep
  src/helpers/.gitkeep
  src/index.ts
  src/interfaces/.gitkeep
  src/middlewares/.gitkeep
  src/models/.gitkeep
  src/queries/.gitkeep
  src/routes/.gitkeep
  src/routes/index.ts
  src/validation/.gitkeep
  tsconfig.json
Labels: awaiting-review

#6 Create database connection & models
  .gitignore
  package-lock.json
  package.json
  src/config/environment.ts
  src/db/build.ts
  src/db/connection.ts
  src/db/index.ts
  src/models/Chat.ts
  src/models/Comments.ts
  src/models/Event.ts
  src/models/Hashtag.ts
  src/models/HashtagEvent.ts
  src/models/InterestedPeople.ts
  src/models/JoinedPeople.ts
  src/models/User.ts
  src/models/index.ts
Labels: approved

#19 Complete database connection, in addition to some bugs
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  src/app.ts
  src/config/environment.ts
  src/db/connection.ts
  src/db/index.ts
  src/index.ts
  src/models/Event.ts
  src/models/User.ts
  test/main.test.ts
  tsconfig.json
Labels: Done

#22 Create fake data and insert them into the database
  package.json
  src/db/FakeData/fakeData.json
  src/db/build.ts
  src/models/Event.ts
Labels: awaiting-review

#23 Create allEvents funtion that filter data by status and start & end time
  .eslintrc.json
  package-lock.json
  package.json
  src/app.ts
  src/config/message.ts
  src/controllers/EventsController.ts
  src/db/FakeData/fakeData.json
  src/db/build.ts
  src/db/connection.ts
  src/routes/index.ts
  test/filterEvents.test.ts
  test/main.test.ts
  tsconfig.json
Labels: approved

#8 [react, mui, css] create login and signUp components and style it
  .eslintrc.json
  client/.eslintrc.json
  client/package-lock.json
  client/src/assets/icons/logo-google.svg
  client/src/assets/images/cover.jpg
  client/src/index.css
  client/src/index.tsx
  client/src/pages/auth/Login.tsx
  client/src/pages/auth/SignUp.tsx
  client/src/pages/auth/auth.css
  client/src/react-app-env.d.ts
Labels: awaiting-review, Component

#24 adding event and its functionality and test
  package-lock.json
  package.json
  src/config/messages.ts
  src/controllers/EventsController.ts
  src/db/build.ts
  src/db/connection.ts
  src/routes/event/index.ts
  src/routes/index.ts
  src/validation/addEventValidate.ts
  test/addEvent.test.ts
  test/filterEvents.test.ts
Labels: approved

#37 make api service with its requests,header and init funciton
  client/src/App.tsx
  client/src/helpers/ApiService.ts
Labels: approved

#39 38 jwt service
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.tsx
  client/src/services/ApiService.ts
  client/src/services/JwtService.ts
  package-lock.json
  package.json
Labels: awaiting-review

#30 setup react router and create all pages
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/pages/Calender/index.tsx
  client/src/pages/Calender/style.css
  client/src/pages/Chat/index.tsx
  client/src/pages/Chat/style.css
  client/src/pages/EventDetails/index.tsx
  client/src/pages/EventDetails/style.css
  client/src/pages/Home/index.tsx
  client/src/pages/Home/style.css
  client/src/pages/Profile/index.tsx
  client/src/pages/Profile/style.css
  client/src/pages/Search Result/index.tsx
  client/src/pages/Search Result/style.css
  client/src/pages/index.tsx
Labels: awaiting-review

#41 create event details function and query and test it
  src/config/messages.ts
  src/controllers/EventsController.ts
  src/interfaces/IFilterEvents.ts
  src/routes/events/index.ts
  src/validation/filterEventValidate.ts
  test/eventsDetails.test.ts
Labels: awaiting-review

#45 [GET / POST] Create joined people routes
  .eslintrc.json
  src/config/messages.ts
  src/controllers/EventParticipantsController.ts
  src/routes/events/index.ts
  src/validation/paramsId.ts
  test/eventJoinedPeople.test.ts
Labels: awaiting-review

#26 create sign up and sign in feature in backend with its tests and validation
  client/package-lock.json
  package-lock.json
  package.json
  src/app.ts
  src/auth/LocalSignIn.ts
  src/config/environment.ts
  src/controllers/signin.ts
  src/controllers/signup.ts
  src/db/FakeData/fakeData.json
  src/db/build.ts
  src/helpers/expressWrapper.ts
  src/helpers/generateToken.ts
  src/helpers/verifyToken.ts
  src/interfaces/IToken.ts
  src/interfaces/IUserRequest.ts
  src/interfaces/payload.ts
  src/interfaces/userData.ts
  src/middlewares/checkUser.ts
  src/models/User.ts
  src/routes/index.ts
  src/validation/signup.ts
  src/validation/validateSignin.ts
  test/signin.test.ts
  test/signup.test.ts
Labels: approved

#48 Create event details page and style it
  client/src/assets/images/commentPic.png
  client/src/assets/images/headerImage.png
  client/src/assets/images/map.png
  client/src/assets/images/profile.png
  client/src/components/AboutEvent/index.tsx
  client/src/components/AboutEvent/style.css
  client/src/components/Comment/index.tsx
  client/src/components/Comment/style.css
  client/src/components/CommentsContainer/index.tsx
  client/src/components/CommentsContainer/style.css
  client/src/components/EventDetailsHeader/index.tsx
  client/src/components/EventDetailsHeader/style.css
  client/src/index.css
  client/src/pages/EventDetails/index.tsx
  client/src/pages/EventDetails/style.css
Labels: awaiting-review

#32 Create FilterCards component with material ui and normal jsx
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/EventCard/index.tsx
  client/src/components/EventCard/style.css
  client/src/components/FilterCard/index.tsx
  client/src/components/FilterCard/style.css
  client/src/interfaces/IEvent.tsx
  client/src/interfaces/IEventDetails.tsx
  client/src/interfaces/index.tsx
  client/src/interfaces/props/EventCardProps.tsx
  client/src/interfaces/props/EventFilterProp.tsx
  client/src/pages/Home/index.tsx
  client/src/services/ApiService.ts
  package-lock.json
  package.json
  src/app.ts
  src/db/FakeData/fakeData.json
Labels: approved

#53 52 auth frontend
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/EventCard/index.tsx
  client/src/components/FilterCard/index.tsx
  client/src/hooks/useAuth.tsx
  client/src/index.tsx
  client/src/interfaces/IAuthContext.tsx
  client/src/interfaces/IUser.tsx
  client/src/interfaces/index.tsx
  client/src/interfaces/props/IAuthContextProps.tsx
  client/src/pages/Home/index.tsx
  client/src/pages/auth/Login.tsx
  client/src/pages/auth/SignUp.tsx
  client/src/services/ApiService.ts
  package-lock.json
  package.json
  src/app.ts
  src/controllers/Auth.ts
  src/controllers/EventsController.ts
  src/controllers/signin.ts
  src/controllers/signup.ts
  src/helpers/expressWrapper.ts
  src/middlewares/isAuth.ts
  src/passport/LocalSignIn.ts
  src/routes/auth/index.ts
  src/routes/events/index.ts
  src/routes/index.ts
  src/validation/paramsId.ts
  test/addEvent.test.ts
  test/signup.test.ts
Labels: approved

#56 54 following system
  src/config/environment.ts
  src/controllers/FollowingSystem.ts
  src/db/FakeData/fakeData.json
  src/models/User.ts
  src/routes/FollowingSystem/index.ts
  src/routes/index.ts
  test/eventJoinedPeople.test.ts
  test/followingSystem.test.ts
Labels: awaiting-review

#46 get/post comments router with its test and handle jwt error in expres…
  src/controllers/CommentsController.ts
  src/db/index.ts
  src/interfaces/IComment.ts
  src/middlewares/checkUser.ts
  src/routes/comments/index.ts
  src/routes/index.ts
  src/validation/addComment.ts
  test/comments.test.ts
Labels: approved

#62 adding sendEmail function in helper folder to send emails
  .github/workflows/tests.yml
  package-lock.json
  package.json
  src/config/environment.ts
  src/helpers/sendingEmail.ts
Labels: approved

#50 Create user profile page functions
  client/.eslintrc.json
  client/src/App.tsx
  client/src/assets/images/Rectangle_2.png
  client/src/components/EditProfile/index.tsx
  client/src/components/EditProfile/style.css
  client/src/components/EditProfile/style.tsx
  client/src/components/EventCard/EventCard.tsx
  client/src/components/EventCard/index.tsx
  client/src/components/EventCard/style.css
  client/src/components/Navbar/DropDown.tsx
  client/src/components/Navbar/index.tsx
  client/src/components/Navbar/style.css
  client/src/components/Navbar/styledMenu.tsx
  client/src/components/UserAudience/index.tsx
  client/src/components/UserAudience/style.css
  client/src/components/UserAudience/style.tsx
  client/src/components/UserProfile/ProfileActions.tsx
  client/src/components/UserProfile/index.tsx
  client/src/components/UserProfile/style.css
  client/src/components/UserProfile/style.tsx
  client/src/hooks/useAuth.tsx
  client/src/index.css
  client/src/interfaces/IAuthContext.tsx
  client/src/interfaces/IUserProfile.tsx
  client/src/interfaces/index.tsx
  client/src/interfaces/props/EventCardProps.tsx
  client/src/interfaces/props/IEditProfile.tsx
  client/src/interfaces/props/IModal.tsx
  client/src/interfaces/props/IProfileActionsProps.tsx
  client/src/interfaces/props/UserProfileProp.tsx
  client/src/pages/Home/index.tsx
  client/src/pages/Profile/index.tsx
  client/src/pages/auth/Login.tsx
  client/src/services/ApiService.ts
  src/config/messages.ts
  src/controllers/EventsController.ts
  src/controllers/FollowingSystem.ts
  src/controllers/UserProfileController.ts
  src/models/User.ts
  src/passport/LocalSignIn.ts
  src/queries/addToUsers.ts
  src/queries/blockUser.ts
  src/queries/deleteFromUsers.ts
  src/queries/getAllUsers.ts
  src/queries/getFromUsers.ts
  src/queries/index.ts
  src/queries/unBlockUser.ts
  src/routes/FollowingSystem/index.ts
  src/routes/index.ts
  src/routes/users/index.ts
  src/validation/EditProfileUpdate.ts
  test/followingSystem.test.ts
  test/signin.test.ts
  test/userProfile.test.ts
Labels: awaiting-review

#59 51 search result component
  client/package-lock.json
  client/src/App.tsx
  client/src/components/Navbar/index.tsx
  client/src/components/SearchResult/EventCard.tsx
  client/src/components/SearchResult/FriendCard.tsx
  client/src/components/SearchResult/index.tsx
  client/src/components/SearchResult/style.css
  client/src/interfaces/IEventCard.tsx
  client/src/interfaces/IFriendCard.tsx
  client/src/interfaces/index.tsx
  client/src/pages/Search Result/index.tsx
  client/src/react-app-env.d.ts
  package-lock.json
  src/controllers/SearchResultController.ts
  src/routes/events/index.ts
Labels: awaiting-review

#68 image uploader component and use it in edit profile component
  client/src/components/EditProfile/index.tsx
  client/src/components/Uploader/index.tsx
  client/src/components/Uploader/style.css
  client/src/components/UserAudience/index.tsx
  client/src/interfaces/props/IUploaderProps.tsx
  client/src/pages/auth/Login.tsx
  client/src/pages/auth/SignUp.tsx
  client/src/services/ApiService.ts
Labels: awaiting-review

#34 20 add event modal
  .env.example
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/components/AddEvent/index.tsx
  client/src/components/AddEvent/style.css
  client/src/components/AddEventMap/index.tsx
  client/src/components/AddEventMap/mapContainer.tsx
  client/src/components/AddEventMap/style.css
  client/src/components/EventDetailsHeader/index.tsx
  client/src/pages/Home/index.tsx
  client/src/validation/addEventValidate.ts
  src/app.ts
  src/controllers/EventsController.ts
  src/controllers/HashtagsController.ts
  src/db/FakeData/fakeData.json
  src/db/index.ts
  src/models/Event.ts
  src/models/Hashtag.ts
  src/routes/events/index.ts
  src/validation/addEventValidate.ts
  test/addEvent.test.ts
Labels: approved

#58 Link backend and frontend Event Details Page
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/components/AboutEvent/index.tsx
  client/src/components/AboutEvent/style.css
  client/src/components/AddCommentsModal/index.tsx
  client/src/components/AddCommentsModal/style.css
  client/src/components/AddEvent/index.tsx
  client/src/components/AddEventMap/mapContainer.tsx
  client/src/components/Comment/index.tsx
  client/src/components/Comment/style.css
  client/src/components/CommentsContainer/index.tsx
  client/src/components/CommentsContainer/style.css
  client/src/components/EventCalendar/index.tsx
  client/src/components/EventCard/EventCard.tsx
  client/src/components/EventDetailsHeader/index.tsx
  client/src/components/EventDetailsHeader/style.css
  client/src/components/JoinedInterestedPeopleModel.tsx/index.tsx
  client/src/components/JoinedInterestedPeopleModel.tsx/style.css
  client/src/components/Map/index.tsx
  client/src/components/Map/style.css
  client/src/components/SearchResult/index.tsx
  client/src/components/Timer/index.tsx
  client/src/components/Timer/style.css
  client/src/helpers/calculateDuration.tsx
  client/src/hooks/useTimer.tsx
  client/src/interfaces/IComments.tsx
  client/src/interfaces/IEventDetails.tsx
  client/src/interfaces/index.tsx
  client/src/interfaces/props/AboutEvent.tsx
  client/src/interfaces/props/CommentsProps.tsx
  client/src/interfaces/props/EventDetails.tsx
  client/src/interfaces/props/IMapProps.tsx
  client/src/interfaces/props/IModalProps.tsx
  client/src/pages/EventDetails/index.tsx
  client/src/pages/EventDetails/style.css
  client/src/react-app-env.d.ts
  client/src/services/ApiService.ts
  src/config/messages.ts
  src/controllers/CalendarJoinedController.ts
  src/controllers/CommentsController.ts
  src/controllers/EventsController.ts
  src/controllers/InterestedController.ts
  src/controllers/JoinedController.ts
  src/db/index.ts
  src/models/Comments.ts
  src/routes/events/index.ts
  src/validation/addComment.ts
  test/addEvent.test.ts
  test/eventInterestedProple.test.ts
Labels: awaiting-review

#67 show events only for my following
  client/src/components/EventCard/index.tsx
  client/src/components/UserAudience/index.tsx
  client/src/interfaces/props/EventCardProps.tsx
  client/src/pages/Profile/index.tsx
  client/src/pages/auth/SignUp.tsx
Labels: awaiting-review

#74 Edit add event modal
  client/package-lock.json
  client/src/components/EventCard/EventCard.tsx
  client/src/components/EventCard/index.tsx
  client/src/services/ApiService.ts
  src/controllers/EventsController.ts
  src/controllers/SearchResultController.ts
  test/eventInterestedProple.test.ts
Labels: awaiting-review

#72 handle error page 404
  client/src/App.tsx
  client/src/components/ErrorPage/index.tsx
  client/src/components/ErrorPage/notFound.png
  client/src/components/ErrorPage/style.css
  client/src/pages/ErrorPage/index.tsx
  client/src/pages/ErrorPage/style.css
  client/src/pages/index.tsx
Labels: awaiting-review

#73 Made landing page, edited navbar styles
  client/src/App.tsx
  client/src/components/CapturePage/index.tsx
  client/src/components/CapturePage/style.css
  client/src/components/Navbar/DropDown.tsx
  client/src/components/Navbar/index.tsx
  client/src/components/Navbar/logo.jpg
  client/src/components/Navbar/logo.png
  client/src/components/Navbar/style.css
  client/src/components/Navbar/styledMenu.tsx
  client/src/pages/LandingPage/index.tsx
  client/src/pages/index.tsx
Labels: awaiting-review

#75 Follow search page upload add event
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/AddCommentsModal/index.tsx
  client/src/components/AddEvent/index.tsx
  client/src/components/AddEventMap/mapContainer.tsx
  client/src/components/Comment/index.tsx
  client/src/components/Comment/style.css
  client/src/components/CommentsContainer/index.tsx
  client/src/components/EditProfile/index.tsx
  client/src/components/EventCard/EventCard.tsx
  client/src/components/JoinedInterestedPeopleModel.tsx/index.tsx
  client/src/components/Navbar/DropDown.tsx
  client/src/components/SearchResult/EventCard.tsx
  client/src/components/SearchResult/FriendCard.tsx
  client/src/components/SearchResult/index.tsx
  client/src/components/SearchResult/style.css
  client/src/components/UserProfile/index.tsx
  client/src/hooks/useFollowing.tsx
  client/src/index.tsx
  client/src/interfaces/IEventCard.tsx
  client/src/interfaces/IFriendCard.tsx
  package-lock.json
  src/controllers/EventsController.ts
  src/controllers/SearchResultController.ts
  src/routes/events/index.ts
Labels: awaiting-review

#80 chang event status every five minutes using node cron
  client/package-lock.json
  package-lock.json
  src/app.ts
  src/controllers/EventsController.ts
  src/cronJobs/ReminderEmail.ts
  src/cronJobs/changeStatus.ts
  src/index.ts
Labels: awaiting-review
